blank_issues_enabled: true
contact_links:
  - name: Question or Discussion
    url: https://github.com/RoyBkker/github-action-vercel-preview-url-poller/discussions
    about: Ask questions or discuss ideas with the community
  - name: Vercel Documentation
    url: https://vercel.com/docs
    about: Official Vercel documentation
  - name: GitHub Actions Documentation
    url: https://docs.github.com/en/actions
    about: Official GitHub Actions documentation
